word = input('Digite algo: ')
ty = type(word)
print('Seu tipo primitivo é: {}'.format(ty))
number = word.isnumeric()
print('É um número? {}'.format(number))
# print('É um número? ', word.isnumeric())
alpha = word.isalpha()
print('É alfabético? {}'.format(alpha))
#print('É alfabético? ', word.isalpha())
alnum = word.isalnum()
print('É alfanumérico? {}'.format(alnum))
lowerr = word.islower()
print('Está tudo em minúsculo? {}'.format(lowerr))
caps = word.isupper()
print('Está tudo em maiúsculo? {}'.format(caps))
space = word.isspace()
print('Só tem espaço? {}'.format(space))
capitalizada = word.istitle()
print('Tem minúsculo e maiúsculo? {}'.format(capitalizada))
